# See https://taskfile.dev/api/
version: "3"

tasks:
  generate:
    aliases:
      - "gen"
    desc: "Generate proto files"
    cmds:
      - rm -rf ${gen}/go/*.go protoc --proto_path=${protos}	--go_out=${gen}/go 	--go_opt=paths=source_relative --go-grpc_out=${gen}/go	--go-grpc_opt=paths=source_relative 	${protos}/*.proto
    silent: true
